import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "id" | "ko";

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    "nav.brand": "Palmignite Charcoal Trade",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.products": "Products",
    "nav.export": "Export",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact",
    "nav.languages.en": "English",
    "nav.languages.id": "Bahasa Indonesia",
    "nav.languages.ko": "한국어",
    "hero.title": "The Gold Standard of Indonesian Charcoal for the Global Market",
    "hero.subtitle": "Your trusted partner for the perfect sear. Delivering world-class BBQ charcoal from Yogyakarta to pitmasters worldwide.",
    "hero.cta": "Request Call",
    "hero.stats.suppliers.label": "Supplier Partners Indonesia",
    "hero.stats.experience.label": "Years Supplier Experiences",
    "hero.stats.quality.label": "Quality",
    "hero.features.quality.title": "Premium Quality",
    "hero.features.quality.desc": "Certified international standards",
    "hero.features.export.title": "Global Export",
    "hero.features.export.desc": "Shipping 15+ countries",
    "hero.features.supplier.title": "Trusted Supplier",
    "hero.features.supplier.desc": "Reliable & consistent delivery",
    "hero.badge.title": "#1 Charchoal Trader",
    "hero.badge.desc": "Leading Barbeque in Indonesia",
    "about.label": "About Us",
    "about.title": "Building a Sustainable Future",
    "about.subtitle": "Our dedication to quality and environmental responsibility drives every step of our process.",
    "about.text": "We are an export trading company focused on selling reliable the best BBQ charcoal briquettes to our business partners worldwide. Our charcoal is produced from selected coconut shells from various regions in Indonesia.",
    "about.facility.title": "World-Class Facility",
    "about.facility.location": "Yogyakarta, Indonesia",
    "about.features.transparency.title": "Transparency",
    "about.features.transparency.desc": "Clear reports and documentation for every shipment.",
    "about.features.consistency.title": "Consistency",
    "about.features.consistency.desc": "Monitored quality for reliable performance.",
    "about.features.sustainability.title": "Sustainability",
    "about.features.sustainability.desc": "100% natural coconut shells, eco-friendly.",
    "about.features.growth.title": "Growth",
    "about.features.growth.desc": "Expanding operations to meet global demand.",
    "products.label": "Technical Specifications",
    "products.title": "Uncompromising Quality",
    "products.subtitle": "Discover the precise standards of our premium charcoal grades.",
    "products.gradeA.title": "Grade A",
    "products.gradeA.desc": "Premium choice for professional grilling and long-lasting heat.",
    "products.gradeAplus.title": "Grade A+",
    "products.gradeAplus.desc": "Balanced composition for versatile usage and consistent performance.",
    "products.specs.ash.label": "Ash Content",
    "products.specs.calories.label": "Calories",
    "products.specs.carbon.label": "Fix Carbon",
    "products.specs.moisture.label": "Moisture",
    "products.specs.volatile.label": "Volatile",
    "products.specs.time.label": "Time Burn",
    "products.badge.bestseller": "BEST SELLER",
    "products.cta": "Request Quote for",
    "products.disclaimer": "* Specifications may vary slightly depending on the raw material batch. Contact us for the most up-to-date lab reports.",
    "export.label": "Global Presence",
    "export.title": "Reaching Across the Globe",
    "export.subtitle": "We take pride in serving international partners across continents with reliable logistics.",
    "export.regions.asia": "Asia",
    "export.regions.europe": "Europe",
    "export.regions.america": "America",
    "export.countries.kr": "South Korea",
    "export.countries.jp": "Japan",
    "export.countries.cn": "China",
    "export.countries.vn": "Vietnam",
    "export.countries.sa": "Saudi Arabia",
    "export.countries.gb": "United Kingdom",
    "export.countries.nl": "Nederland",
    "export.countries.us": "United States",
    "export.stats.countries.label": "Countries Served",
    "export.stats.continents.label": "Continents",
    "export.stats.support.label": "Support",
    "gallery.label": "Our Gallery",
    "gallery.title": "Visual Excellence",
    "gallery.subtitle": "A glimpse into our production process, dedicated team, and premium products.",
    "gallery.categories.production": "Production",
    "gallery.categories.team": "Team",
    "gallery.categories.product": "Product",
    "gallery.categories.logistics": "Logistics",
    "gallery.images.efficient.alt": "Efficient Production Process",
    "gallery.images.teams.alt": "Our Factory Teams",
    "gallery.images.product.alt": "Premium Barbecue Charcoal",
    "gallery.images.safety.alt": "Safe Stuffing Container",
    "gallery.explore": "Explore our world-class facilities and premium products.",
    "gallery.zoom": "Click image to zoom",
    "contact.label": "Get in Touch",
    "contact.title": "Let's Start a Conversation",
    "contact.subtitle": "Ready to elevate your business with premium charcoal? Contact us today.",
    "contact.form.name": "Name",
    "contact.form.namePlaceholder": "John Doe",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "john@example.com",
    "contact.form.phone": "Phone Number",
    "contact.form.phonePlaceholder": "123-456-7890",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Tell us about your needs...",
    "contact.form.submit": "Send Message",
    "contact.info.visit": "Visit Us",
    "contact.info.address": "Jl. Wates Km 3, Ngestiharjo, Kasihan, Bantul, Yogyakarta 55182, Indonesia",
    "contact.info.email": "Email Us",
    "contact.info.call": "Call Us",
    "contact.success": "Message sent successfully!",
    "contact.error": "Failed to send message. Please try again.",
    "footer.company.desc": "Trusted Indonesian charcoal exporter delivering premium-quality products to international standards.",
    "footer.badge": "Premium Charcoal",
    "footer.nav.title": "Navigation",
    "footer.nav.about": "About Us",
    "footer.nav.specs": "Product Specifications",
    "footer.nav.legal": "Legal & Certification",
    "footer.nav.terms": "Terms & Conditions",
    "footer.nav.privacy": "Privacy Policy",
    "footer.contact.title": "Contact",
    "footer.contact.location.label": "Location",
    "footer.contact.location.value": "Yogyakarta, Indonesia",
    "footer.contact.email.label": "Email",
    "footer.contact.whatsapp.label": "WhatsApp",
    "footer.certs.title": "Certifications",
    "footer.certs.quality.label": "Quality Standard",
    "footer.certs.quality.value": "ISO 9001:2015 Certified",
    "footer.certs.legal.label": "Legal Status",
    "footer.certs.legal.value": "Registered Exporter",
    "footer.copyright": "All rights reserved.",
    "notfound.title": "Oops! Page not found",
    "notfound.button": "Return to Home",
  },
  id: {
    "nav.brand": "Palmignite Charcoal Trade",
    "nav.home": "Beranda",
    "nav.about": "Tentang Kami",
    "nav.products": "Produk",
    "nav.export": "Ekspor",
    "nav.gallery": "Galeri",
    "nav.contact": "Kontak",
    "nav.languages.en": "English",
    "nav.languages.id": "Bahasa Indonesia",
    "nav.languages.ko": "한국어",
    "hero.title": "Standar Emas Arang Indonesia untuk Pasar Global",
    "hero.subtitle": "Mitra terpercaya Anda untuk pembakaran sempurna. Mengirimkan arang BBQ kelas dunia dari Yogyakarta ke seluruh dunia.",
    "hero.cta": "Hubungi Kami",
    "hero.stats.suppliers.label": "Mitra Pemasok Indonesia",
    "hero.stats.experience.label": "Tahun Pengalaman Pemasok",
    "hero.stats.quality.label": "Kualitas",
    "hero.features.quality.title": "Kualitas Premium",
    "hero.features.quality.desc": "Standar internasional bersertifikat",
    "hero.features.export.title": "Ekspor Global",
    "hero.features.export.desc": "Pengiriman ke 15+ negara",
    "hero.features.supplier.title": "Pemasok Terpercaya",
    "hero.features.supplier.desc": "Pengiriman handal & konsisten",
    "hero.badge.title": "#1 Pedagang Arang",
    "hero.badge.desc": "Barbeque Terkemuka di Indonesia",
    "about.label": "Tentang Kami",
    "about.title": "Membangun Masa Depan Berkelanjutan",
    "about.subtitle": "Dedikasi kami terhadap kualitas dan tanggung jawab lingkungan mendorong setiap langkah proses kami.",
    "about.text": "Kami adalah perusahaan perdagangan ekspor yang fokus menjual briket arang BBQ terbaik yang handal kepada mitra bisnis kami di seluruh dunia. Arang kami diproduksi dari tempurung kelapa pilihan dari berbagai daerah di Indonesia.",
    "about.facility.title": "Fasilitas Kelas Dunia",
    "about.facility.location": "Yogyakarta, Indonesia",
    "about.features.transparency.title": "Transparansi",
    "about.features.transparency.desc": "Laporan dan dokumentasi jelas untuk setiap pengiriman.",
    "about.features.consistency.title": "Konsistensi",
    "about.features.consistency.desc": "Kualitas terpantau untuk performa handal.",
    "about.features.sustainability.title": "Keberlanjutan",
    "about.features.sustainability.desc": "100% tempurung kelapa alami, ramah lingkungan.",
    "about.features.growth.title": "Pertumbuhan",
    "about.features.growth.desc": "Memperluas operasi untuk memenuhi permintaan global.",
    "products.label": "Spesifikasi Teknis",
    "products.title": "Kualitas Tanpa Kompromi",
    "products.subtitle": "Temukan standar presisi dari grade arang premium kami.",
    "products.gradeA.title": "Grade A",
    "products.gradeA.desc": "Pilihan premium untuk pemanggangan profesional dan panas tahan lama.",
    "products.gradeAplus.title": "Grade A+",
    "products.gradeAplus.desc": "Komposisi seimbang untuk penggunaan serbaguna dan performa konsisten.",
    "products.specs.ash.label": "Kandungan Abu",
    "products.specs.calories.label": "Kalori",
    "products.specs.carbon.label": "Karbon Tetap",
    "products.specs.moisture.label": "Kelembaban",
    "products.specs.volatile.label": "Zat Terbang",
    "products.specs.time.label": "Waktu Bakar",
    "products.badge.bestseller": "PALING LARIS",
    "products.cta": "Minta Penawaran untuk",
    "products.disclaimer": "* Spesifikasi dapat sedikit bervariasi tergantung pada batch bahan baku. Hubungi kami untuk laporan lab terbaru.",
    "export.label": "Kehadiran Global",
    "export.title": "Menjangkau Seluruh Dunia",
    "export.subtitle": "Kami bangga melayani mitra internasional di berbagai benua dengan logistik yang handal.",
    "export.regions.asia": "Asia",
    "export.regions.europe": "Eropa",
    "export.regions.america": "Amerika",
    "export.countries.kr": "Korea Selatan",
    "export.countries.jp": "Jepang",
    "export.countries.cn": "Tiongkok",
    "export.countries.vn": "Vietnam",
    "export.countries.sa": "Arab Saudi",
    "export.countries.gb": "Inggris Raya",
    "export.countries.nl": "Belanda",
    "export.countries.us": "Amerika Serikat",
    "export.stats.countries.label": "Negara Dilayani",
    "export.stats.continents.label": "Benua",
    "export.stats.support.label": "Dukungan",
    "gallery.label": "Galeri Kami",
    "gallery.title": "Keunggulan Visual",
    "gallery.subtitle": "Lihat sekilas proses produksi kami, tim yang berdedikasi, dan produk premium.",
    "gallery.categories.production": "Produksi",
    "gallery.categories.team": "Tim",
    "gallery.categories.product": "Produk",
    "gallery.categories.logistics": "Logistik",
    "gallery.images.efficient.alt": "Proses Produksi Efisien",
    "gallery.images.teams.alt": "Tim Pabrik Kami",
    "gallery.images.product.alt": "Arang Barbeque Premium",
    "gallery.images.safety.alt": "Pemuatan Kontainer Aman",
    "gallery.explore": "Jelajahi fasilitas kelas dunia dan produk premium kami.",
    "gallery.zoom": "Klik gambar untuk memperbesar",
    "contact.label": "Hubungi Kami",
    "contact.title": "Mari Berdiskusi",
    "contact.subtitle": "Siap meningkatkan bisnis Anda dengan arang premium? Hubungi kami hari ini.",
    "contact.form.name": "Nama",
    "contact.form.namePlaceholder": "John Doe",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "john@example.com",
    "contact.form.phone": "Nomor Telepon",
    "contact.form.phonePlaceholder": "0812-3456-7890",
    "contact.form.message": "Pesan",
    "contact.form.messagePlaceholder": "Ceritakan kebutuhan Anda...",
    "contact.form.submit": "Kirim Pesan",
    "contact.info.visit": "Kunjungi Kami",
    "contact.info.address": "Jl. Wates Km 3, Ngestiharjo, Kasihan, Bantul, Yogyakarta 55182, Indonesia",
    "contact.info.email": "Email Kami",
    "contact.info.call": "Hubungi Kami",
    "contact.success": "Pesan berhasil dikirim!",
    "contact.error": "Gagal mengirim pesan. Silakan coba lagi.",
    "footer.company.desc": "Eksportir arang Indonesia terpercaya yang memberikan produk berkualitas premium dengan standar internasional.",
    "footer.badge": "Arang Premium",
    "footer.nav.title": "Navigasi",
    "footer.nav.about": "Tentang Kami",
    "footer.nav.specs": "Spesifikasi Produk",
    "footer.nav.legal": "Legalitas & Sertifikasi",
    "footer.nav.terms": "Syarat & Ketentuan",
    "footer.nav.privacy": "Kebijakan Privasi",
    "footer.contact.title": "Kontak",
    "footer.contact.location.label": "Lokasi",
    "footer.contact.location.value": "Yogyakarta, Indonesia",
    "footer.contact.email.label": "Email",
    "footer.contact.whatsapp.label": "WhatsApp",
    "footer.certs.title": "Sertifikasi",
    "footer.certs.quality.label": "Standar Kualitas",
    "footer.certs.quality.value": "Bersertifikat ISO 9001:2015",
    "footer.certs.legal.label": "Status Hukum",
    "footer.certs.legal.value": "Eksportir Terdaftar",
    "footer.copyright": "Seluruh hak cipta dilindungi.",
    "notfound.title": "Ups! Halaman tidak ditemukan",
    "notfound.button": "Kembali ke Beranda",
  },
  ko: {
    "nav.brand": "Palmignite Charcoal Trade",
    "nav.home": "홈",
    "nav.about": "회사 소개",
    "nav.products": "제품",
    "nav.export": "수출",
    "nav.gallery": "갤러리",
    "nav.contact": "문의하기",
    "nav.languages.en": "English",
    "nav.languages.id": "Bahasa Indonesia",
    "nav.languages.ko": "한국어",
    "hero.title": "글로벌 시장을 위한 인도네시아 숯의 골드 표준",
    "hero.subtitle": "완벽한 시어링을 위한 신뢰할 수 있는 파트너. 요그야카르타에서 전 세계 피트마스터에게 세계적 수준의 BBQ 숯을 제공합니다.",
    "hero.cta": "문의하기",
    "hero.stats.suppliers.label": "인도네시아 공급 파트너",
    "hero.stats.experience.label": "공급업체 경력(년)",
    "hero.stats.quality.label": "품질",
    "hero.features.quality.title": "프리미엄 품질",
    "hero.features.quality.desc": "공인된 국제 표준",
    "hero.features.export.title": "글로벌 수출",
    "hero.features.export.desc": "15개국 이상 수출",
    "hero.features.supplier.title": "신뢰할 수 있는 공급업체",
    "hero.features.supplier.desc": "안정적이고 일관된 배송",
    "hero.badge.title": "#1 숯 무역업체",
    "hero.badge.desc": "인도네시아 최고의 바베큐",
    "about.label": "회사 소개",
    "about.title": "지속 가능한 미래 구축",
    "about.subtitle": "품질과 환경적 책임에 대한 우리의 헌신이 모든 공정 단계를 이끕니다.",
    "about.text": "우리는 전 세계 비즈니스 파트너에게 신뢰할 수 있는 최고의 BBQ 코코넛 숯 브리켓을 판매하는 수출 무역 회사입니다. 우리의 숯은 인도네시아 여러 지역에서 엄선된 코코넛 껍질로 생산됩니다.",
    "about.facility.title": "세계적 수준의 시설",
    "about.facility.location": "인도네시아 요그야카르타",
    "about.features.transparency.title": "투명성",
    "about.features.transparency.desc": "모든 선적에 대한 명확한 보고서 및 문서 제공.",
    "about.features.consistency.title": "일관성",
    "about.features.consistency.desc": "신뢰할 수 있는 성능을 위한 모니터링된 품질.",
    "about.features.sustainability.title": "지속 가능성",
    "about.features.sustainability.desc": "100% 천연 코코넛 껍질, 친환경적.",
    "about.features.growth.title": "성장",
    "about.features.growth.desc": "글로벌 수요를 충족하기 위한 운영 확장.",
    "products.label": "기술 사양",
    "products.title": "타협하지 않는 품질",
    "products.subtitle": "프리미엄 숯 등급의 정밀한 표준을 확인하십시오.",
    "products.gradeA.title": "A 등급",
    "products.gradeA.desc": "전문적인 그릴링과 오래 지속되는 열기를 위한 프리미엄 선택.",
    "products.gradeAplus.title": "A+ 등급",
    "products.gradeAplus.desc": "다양한 용도와 일관된 성능을 위한 균형 잡힌 구성.",
    "products.specs.ash.label": "회분 함량",
    "products.specs.calories.label": "칼로리",
    "products.specs.carbon.label": "고정 탄소",
    "products.specs.moisture.label": "수분",
    "products.specs.volatile.label": "휘발분",
    "products.specs.time.label": "연소 시간",
    "products.badge.bestseller": "베스트셀러",
    "products.cta": "견적 요청:",
    "products.disclaimer": "* 사양은 원료 배치에 따라 약간 다를 수 있습니다. 최신 실험실 보고서는 당사에 문의하십시오.",
    "export.label": "글로벌 입지",
    "export.title": "전 세계로 뻗어나가는 서비스",
    "export.subtitle": "신뢰할 수 있는 물류를 통해 여러 대륙의 국제 파트너에게 서비스를 제공하게 된 것을 자랑스럽게 생각합니다.",
    "export.regions.asia": "아시아",
    "export.regions.europe": "유럽",
    "export.regions.america": "아메리카",
    "export.countries.kr": "대한민국",
    "export.countries.jp": "일본",
    "export.countries.cn": "중국",
    "export.countries.vn": "베트남",
    "export.countries.sa": "사우디아라비아",
    "export.countries.gb": "영국",
    "export.countries.nl": "네덜란드",
    "export.countries.us": "미국",
    "export.stats.countries.label": "서비스 국가",
    "export.stats.continents.label": "대륙",
    "export.stats.support.label": "지원",
    "gallery.label": "갤러리",
    "gallery.title": "시각적 우수성",
    "gallery.subtitle": "우리의 생산 공정, 헌신적인 팀, 프리미엄 제품을 한눈에 확인하십시오.",
    "gallery.categories.production": "생산",
    "gallery.categories.team": "팀",
    "gallery.categories.product": "제품",
    "gallery.categories.logistics": "물류",
    "gallery.images.efficient.alt": "효율적인 생산 공정",
    "gallery.images.teams.alt": "공장 팀",
    "gallery.images.product.alt": "프리미엄 바베큐 숯",
    "gallery.images.safety.alt": "안전한 컨테이너 적재",
    "gallery.explore": "세계적 수준의 시설과 프리미엄 제품을 살펴보십시오.",
    "gallery.zoom": "이미지를 클릭하여 확대",
    "contact.label": "문의하기",
    "contact.title": "상담하기",
    "contact.subtitle": "프리미엄 숯으로 비즈니스를 향상시킬 준비가 되셨습니까? 지금 바로 문의하십시오.",
    "contact.form.name": "이름",
    "contact.form.namePlaceholder": "홍길동",
    "contact.form.email": "이메일",
    "contact.form.emailPlaceholder": "example@email.com",
    "contact.form.phone": "전화번호",
    "contact.form.phonePlaceholder": "010-1234-5678",
    "contact.form.message": "메시지",
    "contact.form.messagePlaceholder": "필요하신 사항을 알려주세요...",
    "contact.form.submit": "메시지 보내기",
    "contact.info.visit": "방문하기",
    "contact.info.address": "Jl. Wates Km 3, Ngestiharjo, Kasihan, Bantul, Yogyakarta 55182, Indonesia",
    "contact.info.email": "Email Kami",
    "contact.info.call": "Hubungi Kami",
    "contact.success": "메시지가 성공적으로 전송되었습니다!",
    "contact.error": "메시지 전송에 실패했습니다. 다시 시도해 주세요.",
    "footer.company.desc": "국제 표준에 부합하는 프리미엄 품질의 제품을 제공하는 신뢰할 수 있는 인도네시아 숯 수출업체입니다.",
    "footer.badge": "프리미엄 숯",
    "footer.nav.title": "네비게이션",
    "footer.nav.about": "회사 소개",
    "footer.nav.specs": "제품 사양",
    "footer.nav.legal": "법적 및 인증",
    "footer.nav.terms": "이용 약관",
    "footer.nav.privacy": "개인정보 처리방침",
    "footer.contact.title": "연락처",
    "footer.contact.location.label": "위치",
    "footer.contact.location.value": "인도네시아 요그야카르타",
    "footer.contact.email.label": "이메일",
    "footer.contact.whatsapp.label": "WhatsApp",
    "footer.certs.title": "인증",
    "footer.certs.quality.label": "품질 표준",
    "footer.certs.quality.value": "ISO 9001:2015 인증",
    "footer.certs.legal.label": "법적 상태",
    "footer.certs.legal.value": "등록된 수출업체",
    "footer.copyright": "모든 권리 보유.",
    "notfound.title": "죄송합니다! 페이지를 찾을 수 없습니다",
    "notfound.button": "홈으로 돌아가기",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
